### ISSUE TITLE
Keypresses aren't sent

### ISSUE THREAD

**Issue by katawful** [Vishram1123/gjs-osk#1]
I installed this on my Lenovo Chromebook Duet running Debian, and have ydotool running on my Wayland session. The extension doesn't seem to complain at all, but no keypresses actually show up when using the keyboard

**Comment by dmxk06** [comment]
having the exact same issue. device is a yoga 7 14arb7

**Comment by dmxk06** [comment]
Ok, so I looked into it a bit, and it appears that ydotool recently had a release where the usage of 'key' was changed. I sadly don't have enough knowledge about javascript, or ydotool to fix this.

**Comment by Vishram1123** [comment]
https://github.com/ReimuNotMoe/ydotool#why-a-background-service-is-needed

**Comment by Vishram1123** [comment]
> I installed this on my Lenovo Chromebook Duet running Debian, and have ydotool running on my Wayland session. The extension doesn't seem to complain at all, but no keypresses actually show up when using the keyboard

I have to add a check for if ydotoold is running

**Comment by Vishram1123** [comment]
If you update to the latest commit, ydotool is no longer need, as the native Clutter.VirtualInputDevice has been implemented.

**Comment by katawful** [comment]
Confirm it works
