### ISSUE TITLE
Bug: Dragging doesn't work well with a pen

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#10]
When I try to drag the keyboard with a pen (which works with touch and mouse input), the keyboard seems to first jump to another place before following my pen:
[Bildschirmaufzeichnung vom 2023-06-03, 16-03-30.webm](https://github.com/Vishram1123/gjs-osk/assets/91820316/a608c11b-abcd-4b9e-9b04-48d283f193fd)

**Comment by Vishram1123** [comment]
It seems that `global.get_pointer` gets the last location of the pointer as moved by the mouse or touchscreen, instead of the location of the stylus. I will try to find a workaround for this.

**Comment by Vishram1123** [comment]
This has been fixed in the latest commit
