### ISSUE TITLE
Switch to specific opening mode when tablet mode is enabled/disabled

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#12]
When I have my Surface Go in laptop mode (keyboard is used) the osk shouldn't pop up when I tap into a text entry but when I'm in tablet mode (keyboard is disconnected or flipped behind the tablet) I want to use the osk. An option that adds the ability to switch to a specific opening mode when in tablet mode and to another when not in tablet mode would solve that.

**Comment by Vishram1123** [comment]
There appears to be no event for when a device switches to tablet mode, so I can't see how to implement this. In the original GNOME OSK, as well as my own OSK (when set in "Open Only on Touch"), it opens only in tablet mode by checking if the last input was by a touchscreen. The difference is that mine doesn't close if another input method is activated. As a workaround, you can put it into "Open Only on Touch" mode, then click with your finger to open, and use your stylus to type.

**Comment by PhilDevProg** [comment]
You can actually check if the hardware tablet-mode switch is enabled with `sudo libinput debug-events --device /dev/input/event12` though I don't think GNOME extensions can run root commands so this would need a systemd daemon that writes the current mode into a variable which the extension then could read maybe every second.

**Comment by PhilDevProg** [comment]
@Vishram1123 How does the autorotate toggle do this? It doesn't seem to check for input methods (at least not for a mouse) since I can use my pen (acting like a mouse) and it doesn't disappear.

**Comment by Vishram1123** [comment]
That seems to be device-specific; my laptop (a Lenovo Yoga) doesn't send switching-to-tablet events at all, so I had to install an extension that would autorotate no matter what.

**Comment by PhilDevProg** [comment]
> That seems to be device-specific; my laptop (a Lenovo Yoga) doesn't send switching-to-tablet events at all, so I had to install an extension that would autorotate no matter what. 

Yeah, my new one doesn't either (Lenovo L13 Yoga Gen 4) since it doesn't support the SW_TABLET_MODE switch. My old Lenovo X1 Yoga Gen 1 supports this switch and it works there so I guess the button checks whether this switch is on or off.
