### ISSUE TITLE
Would it be possible to register a shortcut to toogle the keyboard?

### ISSUE THREAD

**Issue by matovitch** [Vishram1123/gjs-osk#13]
Hello,

I am controlling my linux machine with an xbox gamepad, and using antimicrox I can remap the buttons of the gamepad to some special keys. I would like to be able to toogle the keyboard using such a key, would that be possible ?

Thank you very much for your help and for your nice extension. :)

**Comment by Vishram1123** [comment]
Gonna merge this with #14 because that will be able to solve your issue
