### ISSUE TITLE
Command to open keyboard?

### ISSUE THREAD

**Issue by Ka1zza** [Vishram1123/gjs-osk#14]
Hey there,
Love the keyboard! So far seems to work everywhere.
Just after an easier way to open it. Either with a touchscreen gesture (possible to replace swipe up like GNOME uses for default OSK?)
Or a command would be great too. Will work with fly-pie that way.

Cheers!

**Comment by Vishram1123** [comment]
Will get on this once college applications settle down

**Comment by Ka1zza** [comment]
Thanks mate. Hope everything goes well!

**Comment by Vishram1123** [comment]
@Ka1zza and @matovitch I made this possible in [this commit](https://github.com/Vishram1123/gjs-osk/commit/e416544914d17c20850d741732168e1c710bca26) ([this commit in pre-45](https://github.com/Vishram1123/gjs-osk/commit/5d1e2aec37c2860ebc8b832a49926cf972881c2a)). Now, you can open this keyboard with the command `dconf write /org/gnome/shell/extensions/gjsoskindicator/opened true`. 

@Ka1zza in particular, to accomplish what you want with a gesture, you can use [gestures](https://github.com/natask/gestures#commands-for-touchscreen) to attach running the above command to a touch input.
