### ISSUE TITLE
Broken Name

### ISSUE THREAD

**Issue by in4matix** [Vishram1123/gjs-osk#18]
Gnome 42, the name in TopBar Organizer is broken.

![Screenshot from 2023-09-29 07-26-25](https://github.com/Vishram1123/gjs-osk/assets/62904593/dc2eb082-17c9-4fda-aa35-0615db82c352)

**Comment by Vishram1123** [comment]
Should be fixed now; download the new version, log out and log back in (if you still see the corrupt name, just click on the 3 dots and click "Forget")

**Comment by Vishram1123** [comment]
(Now it should actually be fixed)

**Comment by in4matix** [comment]
Golden, thank you.
