### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by fjsevilla-dev** [Vishram1123/gjs-osk#19]
Hi @Vishram1123, would you be interested in adding translation support to the extension at this point?

If so, would it be also appropriate to add the support to the pre-45 version?

If you are interested I can take care of it if you wish. It is not too much work, just integrate gettext utilities in the code, generate the .pot and add it to a po folder.

**Comment by Vishram1123** [comment]
It would be great if you could do so; I am kinda swamped right now with school and college apps (and probably will be until next school semester (next January)

**Comment by Vishram1123** [comment]
I am going to make the changes requested for submission of the extension, but I am probably not going to touch it at least for a while afterwards.

**Comment by Vishram1123** [comment]
Thanks @fjsevilla-dev for the contributions!
