### ISSUE TITLE
any way to have it display the actual layout?

### ISSUE THREAD

**Issue by dmxk06** [Vishram1123/gjs-osk#2]
even when i select qwerty it uses my system layout which is qwertz. I actually prefer this over not being able to use ä, ö and ü, but is there any way to have it display the layout on the keys themselves?

**Comment by dmxk06** [comment]
I ended up just editing the json myself. Works perfectly now.

**Comment by Vishram1123** [comment]
Could you submit a pr for your edits?

**Comment by Vishram1123** [comment]
Hey, I added QWERTZ in this commit: https://github.com/Vishram1123/gjs-osk/commit/6c0058f25713fc02a55b1381660ba7c5ac52b6b7
