### ISSUE TITLE
Key letters too small

### ISSUE THREAD

**Issue by FearlessSpiff** [Vishram1123/gjs-osk#20]
I have a hidpi display but don´t use scaling. I use Scaling factor under Tweaks -> Font. Maybe this is the problem? Thanks

**Comment by FearlessSpiff** [comment]
Just checked. With 200% scaling it looks great.

**Comment by Vishram1123** [comment]
Glad that you fixed it. Additionally, there is a font size option in the keyboard's settings:
![image](https://github.com/Vishram1123/gjs-osk/assets/64966832/1fa598c0-7b63-47d0-8e16-d02e28202390)
