### ISSUE TITLE
Update version 45 on extension.gnome.org

### ISSUE THREAD

**Issue by yukina3230** [Vishram1123/gjs-osk#25]
Although GJS-OSK has released GNOME 45 version, on extension.gnome.org the latest version is still 44.

**Comment by Vishram1123** [comment]
I know, I tried submitting new versions on extensions.gnome.org, but they rejected it saying I had to make changes for it to be accepted; I am kinda caught up in a lot right now (college apps), so I haven't been able to work on it as of recently. Apologies for any inconvenience this causes.

**Comment by yukina3230** [comment]
Thanks @Vishram1123 , I have no problem using it, just wonder why it hasn't been updated on the extension site yet 😄.  I understand you have a lot of work lately, good luck with your project.

**Comment by Vishram1123** [comment]
I have submitted a new review for gnome 45 as of today, let's see if it gets accepted 🫠

**Comment by Vishram1123** [comment]
I have submitted _yet another_ commit today, (was on vacation and band and stuff as of late and fever and my life is a mess, sorry for the delay), fingers crossed

**Comment by archerallstars** [comment]
The extension is updated on the extensions site. I'm using it now.

![image](https://github.com/Vishram1123/gjs-osk/assets/1403194/4f8dbe3c-c812-4118-a4cf-da3c0550319c)
