### ISSUE TITLE
Key feedback

### ISSUE THREAD

**Issue by enzosanchezewe** [Vishram1123/gjs-osk#27]
It's difficult to know if you are typing correctly without any other feedback than the key getting lighter.
It would help a lot to have a little tap sound and a popup that shows the key that you are pressing (i'll attach an example)
![image](https://github.com/Vishram1123/gjs-osk/assets/62959641/e3916e20-140d-46a9-a003-7755d62de1e2)

**Comment by Vishram1123** [comment]
I added this in the latest commit for the main branch (haven't yet gotten to the pre-45 branch yet)

**Comment by enzosanchezewe** [comment]
Omg i'm on gnome 43.6 due to debian stable. I wanna try it so bad, guess i'll have to wait.
You have made a way better job than the gnome team, congrats. If it werent for you, i wouldn't be able to use my tablet pc.
