### ISSUE TITLE
Turning off the play sound toggle doesn't disable sound on touch input

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#29]
When I turn off the 'Play sound' toggle in the settings and click apply, the sound doesn't get played anymore on mouse or pen input, but on touch input it still gets played.

GNOME version: 45.2
Distribution: Fedora Workstation 39
GJS OSK version: main branch

**Comment by Vishram1123** [comment]
Fixed, will merge after fixing the other issue you mentioned (as well as the comments that the Extensions team gave me a while ago) (sorry was on vacation overseas without my laptop)
