### ISSUE TITLE
Keyboard uses system layout rather than specified one

### ISSUE THREAD

**Issue by katawful** [Vishram1123/gjs-osk#3]
I use US Colemak for my regular keyboard, and I set osk to use Qwerty but it seems to be using colemak despite showing a qwerty layout. This seems to persist with the other 2 layouts available

**Comment by Vishram1123** [comment]
My implementation uses the system keyboard layout and sends inputs from /usr/include/linux/input-event-codes.h, and as a result, the keys sent are unrelated to the keyboard layouts. I will have to change the implementation such that the keyboard layout chosen will correspond to the keys that are pressed. For now, add QWERTY as a keyboard layout and switch to it upon opening the keyboard

**Comment by katawful** [comment]
Thanks, i'll stick with that for now

**Comment by Vishram1123** [comment]
Hey, I fixed this here: https://github.com/Vishram1123/gjs-osk/commit/6c0058f25713fc02a55b1381660ba7c5ac52b6b7
