### ISSUE TITLE
On touch input: Sound gets played multiple times

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#30]
On touch input the sound that gets played when pressing on the keys gets played multiple times. This only happens on touch input and not on mouse or pen input.

Video of the bug (the first two clicks are done by a touchpad, the second two clicks are done via touch input):

[](https://github.com/Vishram1123/gjs-osk/assets/91820316/7f0dbb63-7955-4bd5-b004-083cdd53594d
)

GNOME version: 45.2
Distribution: Fedora Workstation 39
GJS OSK version: main branch

**Comment by Vishram1123** [comment]
[what is wrong with me](https://github.com/Vishram1123/gjs-osk/blob/54bcdcc1e29b7df86fa5c66a78c8d4b9b7140054/gjsosk%40vishram1123.com/extension.js#L984)

**Comment by Vishram1123** [comment]
Will merge after fixing issues noted by gnome extensions team
