### ISSUE TITLE
Feature Request for keyboard colors follows theme

### ISSUE THREAD

**Issue by SnoutBug** [Vishram1123/gjs-osk#31]
In my opinion it would be a great feature if the keyboard followed the systems color theme (light/dark). Since there is already a light themed shell in the works this would match perfectly.

Btw this keyboard is a godsend for 2in1 users, thank you!

**Comment by Vishram1123** [comment]
Implemented in commit mentioned above

**Comment by Vishram1123** [comment]
Unfortunately this doesn't seem to work with Gnome 42, haven't tested with 43, 44, or 46 (should probably still work with 46)

**Comment by SnoutBug** [comment]
That's awesome, thanks!
