### ISSUE TITLE
Question: I installed Block Caribou 36 but it blocks it also on the lock screen

### ISSUE THREAD

**Issue by FearlessSpiff** [Vishram1123/gjs-osk#33]
And GJS-OSK isn't showing there, therefore I can't login. What am I missing? Thanks.

**Comment by FearlessSpiff** [comment]
For anybody reading this. Remove the line `"unlock-dialog"` in the Caribou 36 metadata.json `~/.local/share/gnome-shell/extensions/block-caribou-36@lxylxy123456.ercli.dev/metadata.json` if you don't want the OSK to be blocked there.

**Comment by Vishram1123** [comment]
Thanks for finding the solution! Gonna close this and pin this issue.
