### ISSUE TITLE
Feature request - swipe keyboard integration with gjs-osk

### ISSUE THREAD

**Issue by castleknox** [Vishram1123/gjs-osk#34]
I'd like to donate to this project if and when the developer accepts. There are two features completely absent on the big desktop environments I'd love to help cultivate since gjs-osk has such a strong foundation: swipe keyboards and spellcheck.

**Comment by Vishram1123** [comment]
Unfortunately, I do not take donations. However, if you would like to help with swipe keyboard integration, that would be excellent. As for spellcheck, #6 shows that ibus-typing-booster (which you can install through your distribution's package manager) can provide auto completion and spell checking without the need for extra integration with the keyboard. I am going to change the title to match the feature request for swipe keyboards.

**Comment by ttoommxx** [comment]
Swipe works correctly as the released from last week :) I not sure spell check can be sued from keyboard. If not, you should close this issue as well!

**Comment by Vishram1123** [comment]
Swipe keyboard isn't this?
![image](https://github.com/Vishram1123/gjs-osk/assets/64966832/25fa8e26-d772-446e-b699-280588df301c)

**Comment by ttoommxx** [comment]
Oh I see what you mean now

**Comment by Vishram1123** [comment]
I gotta be honest @castleknox I don't think there is really a feasible way to do this on desktop, and an implementation would require too much undue effort. Apologies, but I'm gonna have to close this as wontfix.
