### ISSUE TITLE
Backward compatibility with gnome 44?

### ISSUE THREAD

**Issue by lp35** [Vishram1123/gjs-osk#35]
Hello,

First I would like to thanks for this project.

I've seen that a lot of dev have been done recently on the main branch.

Any hope to get those updates to the pre-45 release branch? If not, could you expose the technical reasons of it?

Thanks

**Comment by Vishram1123** [comment]
Not really any technical reasons, just that I have been busy with college applications and interviews, school work, etc. I will get to it as soon as possible, sorry for the delay

**Comment by Vishram1123** [comment]
Feature parity should be mostly complete between `main` and `pre-45` now. Outstanding issues are:
1. Key repeat doesn't appear to be working (key press causes focus to be lost, so key press not sent to input box)
2. No easy access to opening mode and indicator placement options on gnome 42 (I don't know how the aggregate menu works in older versions of Gnome, will work on getting that working at some point)

Tested with Ubuntu 22.04 on Gnome 42.9, please let me know if there are any other outstanding problems, especially with gnome 43 and 44.

**Comment by Vishram1123** [comment]
(preferably open a new issue with these outstanding problems)
