### ISSUE TITLE
Split keyboard for tablet mode

### ISSUE THREAD

**Issue by lp35** [Vishram1123/gjs-osk#36]
Hey,

Just a few cents for the layout: it would be very nice to get a split version of the keyboard. This allows, especially on tablet, to be able to type while holding the tablet on the sides.

Here is a screenshot of what GBoard is doing on Android:

https://i1.wp.com/9to5google.com/wp-content/uploads/sites/4/2023/05/Gboard-split-keyboard-tablets-1.jpg

Thanks for yout time, regards

**Comment by Pastitas** [comment]
This would be amazing, as It's very much the only way to comfortably type on it and It would be amazing to get this! 
I'd put some money bounty on it if I can do that (15-20 eur for example)

**Comment by Vishram1123** [comment]
resolved in the commit mentioned above

**Comment by Vishram1123** [comment]
Change the width percent to make the keys smaller or larger

**Comment by Vishram1123** [comment]
(found a bug when changing sizing settings)

**Comment by Vishram1123** [comment]
(and fixed it in commit 8ef37b9
