### ISSUE TITLE
Feature Request: copy/paste keys

### ISSUE THREAD

**Issue by kdw2060** [Vishram1123/gjs-osk#4]
Hi, I don't know it this is technically possible, but I'd like to see copy/paste buttons like they appear on top row of a Android / iOS keyboard. Maybe virtual keys can be bound to ctrl+c / ctrl+v / ctrl+x ?
It's the one feature I miss most compared to true mobile os'es as Gnome also doesn't have a hold to copy/paste feature in general.

**Comment by Vishram1123** [comment]
Sorry it took forever, I didn't see this. I will try to do this sometime in the future. For now, I am busy with school, so this might take a while.

**Comment by Vishram1123** [comment]
I've been trying to get this to work for the past few days, but I can't figure out a way to implement this that would work across different keymaps. Sorry about that, but for now, you can simply lock the control key and press c / x / v to use this same behavior. Sorry about this
