### ISSUE TITLE
Keyboard not working on windows obsured by it

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [Vishram1123/gjs-osk#42]
Left window input issue, right window works as expected

![131804402024](https://github.com/Vishram1123/gjs-osk/assets/17363930/a6eaf6a0-8241-4e2f-8000-59d5cdf135ba)

**Comment by Vishram1123** [comment]
Is this because the window is not in focus? Judging by the fact that the shadow of the right window is above the left window, that may be the case.

**Comment by Vishram1123** [comment]
I have no idea why this is happening, what extensions do you have installed?
<sub>also, thanks for the support</sub>

**Comment by Vishram1123** [comment]
I have no idea why this is happening, and I can't reproduce. Will update if I encounter anything. Sorry for the late response

**Comment by Vishram1123** [comment]
I have noted in the readme that x11 is incompatible, due to the inputmethod manager working differently under x11, so this is probably related to that.
