### ISSUE TITLE
Feature Request: Automatically pop up when tapping into a text field

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#5]
GNOME's default OSK automatically opens in most apps when you just tap into a text field.

**Comment by Vishram1123** [comment]
I've been trying to emulate Gnome OSK's implementation of this for a while now, but I haven't been able to figure it out. Plus, I have always found this incredibly annoying with other OSKs, including the one in Windows and Onboard, but I may revisit this later. However for now, sorry I couldn't implement this.

**Comment by Vishram1123** [comment]
More info will be put in issue #7
