### ISSUE TITLE
Wrong Arrow Keys (German Layout)

### ISSUE THREAD

**Issue by Dr0gelix** [Vishram1123/gjs-osk#51]
Just recently found about this OSK, and what should I say I like it so far, and was pretty much I searched over since the standard OSK from Ubuntu isn't that good when you have a 2in1 convertible. But so far I came across these faults so far:

Arrow Up – scrolls down
Arrow Left – scrolls up
Arrow Down – moves cursor on searchbar (the text) one letter to the left
Arrow Right – seems to be alright

**Comment by Vishram1123** [comment]
Has been fixed in the latest commit/version on the Extensions hub

**Comment by Vishram1123** [comment]
Try updating and letting me know, then I will close this

**Comment by Dr0gelix** [comment]
> Try updating and letting me know, then I will close this

When I first installed this extension with the extension manager there was no update. After I read your post, opened the notebook, and got notified immediately about the update.

It is fixed now, thank you, very much appreciated.
