### ISSUE TITLE
Special Keys

### ISSUE THREAD

**Issue by rogercreagh** [Vishram1123/gjs-osk#55]
Could the special keys (Ctrl, Fn, Super, Alt) possibly use text rather than icons. This could be an option maybe with the text configurable by the user. The icons used don't match what is on any (UK layout) I use - they all have text which is much clearer.

Using Ubuntu 24.04 on a StarLite laptop I actually have 4 physical keys to the left of the space bar - it is not at all clear how they map to your icons so I have no idea which is which. They are labelled `Ctrl`  `fn` `super` and `alt`. I think your middle key might be `super` but I'm not sure what the other two are.

**Comment by Vishram1123** [comment]
Sure, I just made them icons because when the keyboard is too small, the text is cut off.

**Comment by Vishram1123** [comment]
Gonna close this because #54 essentially refers to the same thing

**Comment by Vishram1123** [comment]
Added a toggle in the settings in 1fad5fd to turn off the icons and replace them with text
