### ISSUE TITLE
Keyboard loosing focus when missing a key hit

### ISSUE THREAD

**Issue by guillerolle** [Vishram1123/gjs-osk#58]
Hey, first of all, I want to thank you some for this project. It's really great.
I will open up just various different issues for a couple of bugs I've found or just suggestions:

When I'm typing and I miss a key, maybe hitting in the space in-between keys or on the borders of the keyboard (but on the keyboard anyways), the actual input event goes to the window behind the keyboard and the keyboard automatically minimize because it has lost focus and I end up clicking on a lot of things I didn't want to. It makes it a bit unpredictable and dangerous in fact.

I could provide more details if you need. Thanks

**Comment by Vishram1123** [comment]
I notice that this happens in Overview, but not in applications or on the desktop (this is using Opening mode: Always, will patch this), what app are you using that causes the keyboard to minimize?

**Comment by guillerolle** [comment]
> I notice that this happens in Overview, but not in applications or on the desktop (this is using Opening mode: Always, will patch this), what app are you using that causes the keyboard to minimize?

I didn't notice if it's different behaviour depending on the app. I will take a look at that later but on Firefox for sure it happens a lot to me a lot as yesterday I wrote these issues here on the tablet and really struggled to do it because of this reason. I have Ubuntu 24.04 and Firefox snap on the tablet

**Comment by guillerolle** [comment]
This is on Wayland. It also happens quite a lot when using the gnome terminal. On gedit it worked fine, though. All of this was tested with the "Always" opening mode

**Comment by Vishram1123** [comment]
Can't seem to reproduce this... which autorelease are you using? (Look in GJS-OSK's settings -> About)

**Comment by guillerolle** [comment]
Hi, sorry. I've been out for some weeks and didn't have the tablet with me.
Autorelease is fab8e97.

**Comment by dexterdy** [comment]
i also have a similar issue. When I tap in between two keys in the margin or in other empty space on the keyboard, the software loses focus of whatever text field I was typing in. Very reproducible with the split keyboard, but tapping the rather space left by the jagged rows of keys where it is cut in two.

**Comment by dexterdy** [comment]
I would also like to suggest making the keyboard register a keypress of whatever key is closest to where I tap on the keyboard. I end up missing quite a lot of keys because I tap the whitespace instead of the button.

**Comment by Vishram1123** [comment]
Fixed in the latest series of commits (or should be, please respond if it doesn't work)
