### ISSUE TITLE
Feature Request: Auto completion (via ibus-typing-booster?)

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#6]
GNOME's default OSK has auto completion for languages which don't require ibus and uses [ibus-typing-booster](https://github.com/mike-fabian/ibus-typing-booster)  for the remaining ones although I don't know if it's technically possible to use ibus-typing-booser for this.

**Comment by kdw2060** [comment]
fyi: on my system (Fedora 36) and without special settings the typing booster pops up automatically when using gjs-osk and I can choose one of the suggestions by either tapping them or using the function keys of gjs-osk

**Comment by Vishram1123** [comment]
> fyi: on my system (Fedora 36) and without special settings the typing booster pops up automatically when using gjs-osk and I can choose one of the suggestions by either tapping them or using the function keys of gjs-osk

Tried that on my system and it works (incredibly annoying, but it works). I have no plans of integrating this functionality directly into gjs-osk, but I will add a section to the README detailing how to set it up.

> oh, I did install the latest branch from the repo here and not the version that's available via gnome-extensions website, don't know if that makes a difference

...where did you find it on the extension website, I haven't published it

**Comment by Vishram1123** [comment]
> GNOME's default OSK has auto completion for languages which don't require ibus and uses [ibus-typing-booster](https://github.com/mike-fabian/ibus-typing-booster) for the remaining ones although I don't know if it's technically possible to use ibus-typing-booser for this.

I don't have plans to integrate this into my keyboard, but I added a section to the README [here](https://github.com/Vishram1123/gjs-osk/commit/b648fc54aaba855aa0191f7d398bdae1505f1d5e) explaining how @kdw2060 got this working.

**Comment by kdw2060** [comment]
> ...where did you find my extension on the extension website, I haven't published it

Think that was a memory-lapse from me. Probably assumed this because once installed it shows up in the extension manager application like all other extensions that you can install from within the manager.
