### ISSUE TITLE
Feature request: transparency

### ISSUE THREAD

**Issue by guillerolle** [Vishram1123/gjs-osk#60]
I find the keyboard borders too thick and I've been thinking that having a transparency control for the whole keyboard would be good for looking at something behind the keyboard without dragging or closing it

**Comment by Vishram1123** [comment]
Change the color in the preferences to a color that has transparency (using the slider at the bottom when using the fine-tune picker): 
![image](https://github.com/user-attachments/assets/e389abeb-fdad-41e2-94ad-39e627da03b1)

**Comment by guillerolle** [comment]
Well I don't know how I missed so many of these settings... Apologies
