### ISSUE TITLE
Layout doesn't change

### ISSUE THREAD

**Issue by ralex2304** [Vishram1123/gjs-osk#61]
Keyboard layout appearance on OSK doesn't change when I switch it (both via Super+Space and gnome GUI). However, correct symbols are typed. So I think problem is in refresh condition. It seems that "org.gnome.desktop.input-sources.current" index is deprecated.

Details:
- Gnome 46, Wayland
- Arch Linux
- Keyboard layouts: US, RU

**Comment by olekyd** [comment]
I have the same issue

**Comment by svff3r** [comment]
Same.
The OSK only changes layout appearance when you change keyboard layout in the extension settings or when you modify something in the Input Sources settings.
Fresh EndeavourOS installation, GNOME 46 (Wayland).

**Comment by Vishram1123** [comment]
Seems that this is an arch-specific issue - will look into this in a little bit - moving into college

**Comment by Vishram1123** [comment]
It seems that it works on arch, what version are you using @olekyd @ralex2304 @svff3r?

**Comment by Vishram1123** [comment]
> It seems that "org.gnome.desktop.input-sources.current" index is deprecated.
My extension doesn't make use of this key

**Comment by ralex2304** [comment]
> It seems that it works on arch, what version are you using @olekyd @ralex2304 @svff3r?

GJS OSK version 27 autorelease fab8e97

> > It seems that "org.gnome.desktop.input-sources.current" index is deprecated.
> 
> The extension doesn't make use of this key

I'm not sure about it, but I've found this:

https://github.com/Vishram1123/gjs-osk/blob/2506a863b277339805519bca06d1b101cf92eb32/gjsosk%40vishram1123.com/extension.js#L133

As far as I understand all keys of `org.gnome.desktop.input-sources` don't change on layout switch

**Comment by Vishram1123** [comment]
It seems that this key was indeed deprecated; I have switched to using Gnome's built-in InputSourceManager instead of relying on the GSettings key.

**Comment by ralex2304** [comment]
Thanks! It works now
