### ISSUE TITLE
Specific layout for portait and landscape

### ISSUE THREAD

**Issue by BadCo-NZ** [Vishram1123/gjs-osk#62]
Hi, just started using this on my Surface Pro. I noticed it would be useful to have different keyboards for Landscape (TKL) and Portrait (Compact).

Thanks for your efforts so far!

**Comment by Vishram1123** [comment]
Will look into this in a little bit - moving into college

**Comment by BadCo-NZ** [comment]
Nice one, I look forward to trying it
