### ISSUE TITLE
Keyboard layout changed since a few versions back

### ISSUE THREAD

**Issue by g3blv** [Vishram1123/gjs-osk#63]
I noticed that the keyboard layout changed since a few versions back (please see screenshot). I now have an extra top row, I'm missing the button to move the keyboard, and the whole keyboard feels more cramped. I had a look in setting, but I haven't been able to find any setting to revert to the "old" layout (like the layout shown in Keyboard.Demo.webm). Any suggestion how I can get the hold layout back?

![Screenshot from 2024-08-21 21-25-24](https://github.com/user-attachments/assets/7feed153-4780-4512-b2a7-7ec290b20089)

**Comment by Vishram1123** [comment]
Sorry, I changed this permanently; to move the keyboard around the screen, drag the bar at the top center. If you wish to revert back to the old layout, you can install [Autorelease 9548af7](https://github.com/Vishram1123/gjs-osk/releases/tag/9548af7)
