### ISSUE TITLE
Doesn't work for gdm3 login

### ISSUE THREAD

**Issue by Phiznlil** [Vishram1123/gjs-osk#64]
I want this to be the default in the gdm3 login screen, also, instead of the default OSK. Is this possible?

**Comment by Vishram1123** [comment]
Add the following to `metadata.json` in your gjs-osk extension folder:
```
"session-modes" : [
  "user",
  "unlock-dialog"
],
```
see #56 to see why I didn't implement this by default

**Comment by Phiznlil** [comment]
Many thanks, that works.

I realize now that it is a local extension and, therefore, can't be enabled
on the initial login screen. However, it does make it much easier to type a
password that contains alternating letters and numbers than with the
default OSK, which is why I wanted it.
