### ISSUE TITLE
split keyboard configuration option suggestion

### ISSUE THREAD

**Issue by dexterdy** [Vishram1123/gjs-osk#65]
I really like the split keyboard, but I'm noticing that it doesn't quite match the way I type. Would it be possible to add an option to move the 'y g v' column of keys to the right side of the screen?

**Comment by Vishram1123** [comment]
I added a mobile and split mobile layout that you may prefer in https://github.com/Vishram1123/gjs-osk/commit/bd44cc6c2d8fe8595fbe89ae3b6a03a1b994d7eb that are closer to Google's GBoard.
