### ISSUE TITLE
don't lose focus when mistyping a letter

### ISSUE THREAD

**Issue by dexterdy** [Vishram1123/gjs-osk#66]
When you accidentally miss a key and land on the margin between keys, the program loses focus of whatever text field I'm typing in, and I have to go back and click it again in order to keep typing. It would also be nice if the keyboard registered a keypress of the closest button when hitting a margin, rather than nothing at all.

**Comment by dexterdy** [comment]
noticed that this is a duplicate

**Comment by Vishram1123** [comment]
Fixed in the latest series of commits
