### ISSUE TITLE
[Feature request] Automatically open keyboard when in text field

### ISSUE THREAD

**Issue by KCGD** [Vishram1123/gjs-osk#7]
This keyboard is much better than gnome's built-in osk. However, one feature I really liked about the default osk is (in touchscreen mode) it opens automatically when you enter a text field. Is there any way to add that feature to this keyboard?

**Comment by Vishram1123** [comment]
Please see #5; I will try to implement this, but right now my priority is getting the keyboard ready to be shipped on extensions.gnome.org (and not failing my finals), so this might take a bit longer to implement.

**Comment by KCGD** [comment]
> and not failing my finals

Understandable, take all the time you need :)

**Comment by Vishram1123** [comment]
I have been breaking my head trying to do this all day, and I haven't figured out how to do this...

**Comment by Vishram1123** [comment]
Check [this branch](https://github.com/Vishram1123/gjs-osk/tree/auto-open), it has rudimentary automatic opening working (to an extent, only working very unreliably in certain applications

**Comment by KCGD** [comment]
I'll give it a shot!

**Comment by KCGD** [comment]
ok, so I tried the auto open branch but the keyboard did not open for anything (I tested firefox, gnome terminal, the activities menu searchbar, and gnome's settings) all in native wayland. I also tried mailspring just to see what how an xwayland program would act but same thing.

**Comment by Vishram1123** [comment]
Interesting; it not that dysfunctional for me, but the only app it worked in properly was Thunderbird. I will have to modify my approach significantly.

**Comment by KCGD** [comment]
Already reverted for now.

Could you please give me some info on how you test the auto-open branch? I'm a bit new to this and I want to make sure that I did it correctly.

**Comment by Vishram1123** [comment]
I would just delete the existing version, clone the repo, checkout the auto-open branch (`git checkout -b auto-open`), copy gjsosk@vishram1123.com to ~/.local/share/gnome-shell/extensions, logout, and log back in.

Side note - I am going to implement four-finger tap for now, as the automatic opening isn't quite working

**Comment by KCGD** [comment]
Ok that's good. That's pretty much what I did.

If I have some free time I might take a crack at it. I'll open up a PR if I find anything interesting. Thanks for looking into this :)

**Comment by Vishram1123** [comment]
I added an option for now to open with a four-finger tap (5 fingers on the desktop for some reason, it is a similar case with switching between desktops, requires 4 fingers on the desktop but three fingers in the app switcher and app grid, seems to be the way that the clutter.gestureaction has been implemented). I may remove this later in favor of the text field opening, but for now it is a better alternative to opening using the button in the top bar.

**Comment by PhilDevProg** [comment]
> Interesting; it not that dysfunctional for me, but the only app it worked in properly was Thunderbird. I will have to modify my approach significantly.

It also works in Krita (maybe Qt apps in general) for me.

**Comment by Vishram1123** [comment]
I got it to work when tapping to open, could someone test it to make sure it works?

**Comment by PhilDevProg** [comment]
> I got it to work when tapping to open, could someone test it to make sure it works?

It works for me with all apps (Firefox, GNOME Text Editor, GNOME Settings, ...) except Qt apps.

**Comment by Vishram1123** [comment]
> It works for me with everything (Firefox, LibreOffice, GNOME Text Editor, GNOME Settings, Shell Search Entry, ...) except Qt apps, the folder name entry in the App Grid and the WiFi password dialog of the Shell.
Qt apps won't work because of [this](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6015) (tldr: text_input_unstable_v3 support refused by Qt, instead unsupported v4 is implemented), but I will try to get the dialogs to work. I can't figure out how the default OSK is able to grab focus as of right now... the keyboard can display at the same layer as these dialogs, but its "hitbox" (idk what to call it) is beneath. 

> Maybe the user could also switch between them in a menu in the quick settings like in the power profiles menu if https://github.com/Vishram1123/gjs-osk/issues/8 gets implemented.
Implemented in the [latest commit](https://github.com/Vishram1123/gjs-osk/commit/c9ba10827e183ed86c4686f5029395b75e918608)

**Comment by Vishram1123** [comment]
For now I am closing this, and moving the above mentioned dialog issue to a new issue

**Comment by castleknox** [comment]
> Check [this branch](https://github.com/Vishram1123/gjs-osk/tree/auto-open), it has rudimentary automatic opening working (to an extent, only working very unreliably in certain applications). EDIT: Please only use this for testing, as it isn't stable yet.

Out of curiosity, is it possible to implement a fix in the extension to disable the default Gnome OSK when GJS-OSK is enabled?

**Comment by Vishram1123** [comment]
@castleknox done in 828ecdbb6d514a15347a5447d2f563bb4b69e9b7, sorry this didn't see this until now
