### ISSUE TITLE
Extension stops reponding after every reboot

### ISSUE THREAD

**Issue by in4matix** [Vishram1123/gjs-osk#70]
Hi, After reboot, It produces this error:

![Screenshot from 2024-09-20 16-03-31](https://github.com/user-attachments/assets/79c72e53-2074-4084-bf73-d999803913ac)

Then I disable it, reboot again, then enable it, then it works fine until next reboot.

Gnome 42.9 (Ubuntu 22.04 LTS) Wayland

**Comment by in4matix** [comment]
Just an update.
I uninstalled the version from Gnome extensions website, downloaded and installed the latest release from here, and can confirm that this has resolved the issue.

![Screenshot from 2024-09-20 18-42-03](https://github.com/user-attachments/assets/bcf8c153-d612-493c-8fae-7e246a485541)

**Comment by Vishram1123** [comment]
Good to know, I will close this. I need to update the upstream version, once I fix the bugs previously mentioned.
