### ISSUE TITLE
External display issue

### ISSUE THREAD

**Issue by milan445** [Vishram1123/gjs-osk#71]
On my Asus Vivo AIO 16 V161GA_A41GA 1.0 with built-in touchscreen display keyboard works just fine. However, when external display is connected, for some reason keyboard constantly show on that display. Is there a possibilty of adding an option to toggle the default display?

**Comment by Vishram1123** [comment]
I added options in preferences to choose the display to show GJS-OSK on in https://github.com/Vishram1123/gjs-osk/commit/f91fd56addd58a7fca8739d157716b3be1bd1a60
