### ISSUE TITLE
Make The Keyboard Reflect Keys Presseed On Physical Keyboard

### ISSUE THREAD

**Issue by zacccharv** [Vishram1123/gjs-osk#72]
A nice feature of the Windows OSK is its highlighting of keys currently pressed on the actual keyboard. 
This would be nice for when you press and hold a modifier key like Shift, Ctrl or Super. 
Also if it could show the alternative keys that appear when Shift is pressed, similar to Caps Lock, that would be a nice bonus as well.

**Comment by Vishram1123** [comment]
It doesn't show the alternate keys currently? Also, I will see if it is possible to track the current key pressed once I get the time, but that might be computationally intensive.

**Comment by Vishram1123** [comment]
Please see my comments on #75. TL;DR, I don't feel that this is the aim of GJS-OSK, and might create another extension.
