### ISSUE TITLE
Modifier keys pressed.

### ISSUE THREAD

**Issue by Raniuss** [Vishram1123/gjs-osk#73]
It would be interesting to be able to hold down a modifier key continuously I give an example for everyone: 
Let's say we want to select multiple icons by Shift key held down and then left mouse click. Right now, maybe because of me not knowing how to do it, every time I have to repress Shift and then mouse click. Instead, it would be interesting for Shift to stay pressed until I deactivate it.

I apologize in advance for my ignorance.

**Comment by Vishram1123** [comment]
No problem, it isn't ignorance; I haven't implemented this. I will do this once I get the time.

**Comment by Vishram1123** [comment]
Hey, I implemented this in commit https://github.com/Vishram1123/gjs-osk/commit/e593931b13c1e2633f451b747a987c6c02ac6df3
