### ISSUE TITLE
Display keyboard command does not work

### ISSUE THREAD

**Issue by Katsuyamaki** [Vishram1123/gjs-osk#74]
dconf write /org/gnome/shell/extensions/gjsosk/indicator/opened true

I typed the command above in terminal and nothing happens. There is no error in terminal and my OSK keyboard does not pop up. It had worked before but suddenly stopped working and I can't get it to work again even with uninstalling and reinstalling the extension.

**Comment by Vishram1123** [comment]
@Katsuyamaki Please let me know the command's output and which version of Gnome and GJS-OSK you are using if you are still experiencing the issue

**Comment by Katsuyamaki** [comment]
I ended up reinstalling gnome and gjs-osk to get it to work. Seems it's working now and I haven't been able to reproduce the issue anymore.

**Comment by Katsuyamaki** [comment]
@Vishram1123 

Hello - this issue is happening again. Even if I reboot my pc, the keyboard doesnt show up. Here is the dump command results:

[/]
background-a=1.0
background-a-dark=1.0
background-b=250.0
background-b-dark=50.0
background-g=250.0
background-g-dark=50.0
background-r=250.0
background-r-dark=50.0
border-spacing-px=1
default-monitor='1:DP-2'
default-snap=7
enable-drag=true
enable-tap-gesture=1
font-bold=false
font-size-px=8
indicator-enabled=true
landscape-height-percent=20
landscape-width-percent=20
layout=5
layout-landscape=8
layout-portrait=8
outer-spacing-px=16
play-sound=true
portrait-height-percent=25
portrait-width-percent=50
round-key-corners=false
show-icons=true
snap-spacing-px=20
system-accent-col=false

[indicator]
opened=true
