### ISSUE TITLE
Incompatible with GNOME 47.1 (Xorg)

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [Vishram1123/gjs-osk#76]
![Screenshot From 2024-11-02 16-55-00](https://github.com/user-attachments/assets/74ce5a78-d1d9-4c7c-9b89-39be275e59a1)

**Comment by Vishram1123** [comment]
Firstly, this is a duplicate. Check #69 for more details.
Secondly, this keyboard does not support xorg (as I mentioned in the comment in your screenshot).
