### ISSUE TITLE
Feature Request: Add toggle in quick settings

### ISSUE THREAD

**Issue by yukina3230** [Vishram1123/gjs-osk#8]
I like this extention, very useful.
But for those who have a lot of tray icons, I find it quite good to add a toggle to quick settings like this: [OSK Toggle](https://extensions.gnome.org/extension/5922/osk-toggle/).
Please consider, thank you.

**Comment by Vishram1123** [comment]
Right now, this keyboard doesn't open and close automatically, so once I implement that, I will add a toggle that will either place the keyboard in the quick settings or the tray

**Comment by Vishram1123** [comment]
Hey, I implemented this in the [latest commit](https://github.com/Vishram1123/gjs-osk/commit/c9ba10827e183ed86c4686f5029395b75e918608)
